# Generated by Django 3.2.5 on 2021-07-08 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headmates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pronouns', models.CharField(blank=True, max_length=100, null=True)),
                ('host', models.BooleanField(default=False)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('age_increments', models.BooleanField(default=False)),
                ('age_slide', models.BooleanField(default=False)),
                ('arrival_day', models.DateField(blank=True, null=True)),
                ('proxy', models.CharField(blank=True, max_length=20, null=True)),
                ('species', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('sexuality', models.CharField(blank=True, max_length=50, null=True)),
                ('roles', models.CharField(blank=True, max_length=100, null=True)),
                ('tells', models.CharField(blank=True, max_length=100, null=True)),
                ('triggers', models.CharField(blank=True, max_length=200, null=True)),
                ('about_me', models.TextField(blank=True, null=True)),
                ('fusion_of', models.CharField(blank=True, max_length=200, null=True)),
                ('appearance', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
