# Generated by Django 3.2.5 on 2021-07-16 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(blank=True, max_length=50, null=True)),
                ('public_name', models.CharField(blank=True, max_length=50, null=True)),
                ('body_age', models.IntegerField(blank=True, null=True)),
                ('phone_num', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('medical_info', models.TextField(blank=True, null=True)),
                ('hobbies_interests', models.TextField(blank=True, null=True)),
                ('profile_of', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Headmates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('front', models.BooleanField(default=False)),
                ('pronouns', models.CharField(blank=True, max_length=100, null=True)),
                ('host', models.BooleanField(default=False)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('age_increments', models.BooleanField(default=False)),
                ('age_slide', models.BooleanField(default=False)),
                ('arrival_day', models.DateField(blank=True, null=True)),
                ('proxy', models.CharField(blank=True, max_length=20, null=True)),
                ('species', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('sexuality', models.CharField(blank=True, max_length=50, null=True)),
                ('roles', models.CharField(blank=True, max_length=100, null=True)),
                ('tells', models.CharField(blank=True, max_length=100, null=True)),
                ('triggers', models.CharField(blank=True, max_length=200, null=True)),
                ('about_me', models.TextField(blank=True, null=True)),
                ('fusion_of', models.CharField(blank=True, max_length=200, null=True)),
                ('appearance', models.TextField(blank=True, null=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headmates', to='system.profile')),
            ],
        ),
    ]
