# Generated by Django 3.2.5 on 2021-07-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='headmates',
            name='front',
            field=models.BooleanField(default=False),
        ),
    ]
